#! /bin/sh

#个人使用的快捷命令

#登陆
alias sshserver='ssh magneto@192.168.40.34'

#数据库
alias db='mysql -uroot -proot123 -h192.168.40.10'

#lc0-lc5
alias lc0='ssh magneto@192.168.40.80'
alias lc1='ssh magneto@192.168.40.81'
alias lc2='ssh magneto@192.168.40.82'
alias lc3='ssh magneto@192.168.40.83'
alias lc4='ssh magneto@192.168.40.84'
alias lc5='ssh magneto@192.168.40.85'


#commands
alias ..='cd ..'
alias ...='cd ../..'

extract() {
    if [ -f $1 ] ; then
      case $1 in
        *.tar.bz2)   tar xjf $1     ;;
        *.tar.gz)    tar xzf $1     ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar e $1     ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xf $1      ;;
        *.tbz2)      tar xjf $1     ;;
        *.tgz)       tar xzf $1     ;;
        *.zip)       unzip $1       ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *)     echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

alias meminfo='free -m -l -t'
alias ps?="ps aux | grep"

#显示出活动的端口
alias port='netstat -tulanp'

#绘制内核模块依赖曲线图。需要可以查看图片
kernelgraph() { lsmod | perl -e 'print "digraph \"lsmod\" {";<>;while(<>){@_=split/\s+/; print "\"$_[0]\" -> \"$_\"\n" for split/,/,$_[3]}print "}"' | dot -Tpng | display -;}

#查找历史命令
alias histg='history | grep'

#在右上角打印时钟
alias pt='while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &'

#打印最耗费内存的四个进程
alias mm='ps aux | sort -nk +4 | tail'

#git
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
